exclude: '^($|.*\.bin)'
fail_fast: false

repos:
    - repo: https://github.com/asottile/seed-isort-config
      rev: v2.2.0
      hooks:
          - id: seed-isort-config
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-json
          - id: pretty-format-json
          - id: check-merge-conflict
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: debug-statements
          - id: end-of-file-fixer
          - id: mixed-line-ending
            args: ['--fix=crlf']
          - id: name-tests-test
          - id: requirements-txt-fixer
          - id: sort-simple-yaml
          - id: trailing-whitespace
          - id: check-symlinks
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
          - id: isort
    - repo: https://github.com/ambv/black
      rev: 22.3.0
      hooks:
          - id: black
            args: [--safe, --quiet]
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            additional_dependencies: [flake8-blind-except, flake8-bugbear, flake8-comprehensions, flake8-debugger, flake8-docstrings, flake8-isort, flake8-polyfill, flake8-pytest, flake8-quotes, yesqa, wemake_python_styleguide]
    - repo: local
      hooks:
          - id: pytest-cov
            name: pytest Cov
            language: system
            entry: pytest test/unittests --cov=game_of_life --cov-fail-under=90 --cov-branch
            types: [python]
            pass_filenames: false
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: ''  # Use the sha / tag you want to point at
      hooks:
          - id: mypy
    - repo: https://github.com/asottile/blacken-docs
      rev: v1.12.1
      hooks:
          - id: blacken-docs
            additional_dependencies: [black==20.8b1]
    - repo: https://github.com/terrencepreilly/darglint
      rev: v1.8.1
      hooks:
          - id: darglint
    - repo: https://github.com/asottile/pyupgrade
      rev: v2.34.0
      hooks:
          - id: pyupgrade
    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.9.0
      hooks:
          - id: python-check-blanket-noqa
          - id: python-check-mock-methods
          - id: python-no-eval
          - id: python-no-log-warn
